// <auto-generated />
using System;
using MevGovernanceBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace mevgovernancebackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260709115220_AddCollaudoColumnsToConsumoTow")]
    partial class AddCollaudoColumnsToConsumoTow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("MevGovernanceBackend.Models.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastAlignAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("MevGovernanceBackend.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLogout")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SendEmail")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MevGovernanceBackend.Models.BuonoConsegna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Avanzato")
                        .HasColumnType("TEXT");

                    b.Property<string>("Contratto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DaAvanzare")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Importo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Oda")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RifContratto")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BuoniConsegna");
                });

            modelBuilder.Entity("MevGovernanceBackend.Models.ConsumoTow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Approvato")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Impegnato")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OrdinatiRda")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Residuo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tow")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TowApprovati")
                        .HasColumnType("TEXT");

                    b.Property<string>("TowContratto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TowImpegnati")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TowResidui")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValoreTotale")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValoreUnitario")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConsumoTow");
                });

            modelBuilder.Entity("MevGovernanceBackend.Models.Contratto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Avanzato")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DaAvanzare")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DaOrdinare")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImpLordo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImportoNetto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Ordinato")
                        .HasColumnType("TEXT");

                    b.Property<string>("RifContratto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Sconto")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoContratto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contratti");
                });

            modelBuilder.Entity("MevGovernanceBackend.Models.MevItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnnoCompetenza")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Applicativo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AtId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Capgemini")
                        .HasColumnType("TEXT");

                    b.Property<string>("Contratto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExcelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExcelOrder")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Fatturato")
                        .HasColumnType("TEXT");

                    b.Property<string>("GoTo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Iet")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImportoExcel")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteExcel")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OrdinatoBdo")
                        .HasColumnType("TEXT");

                    b.Property<int>("PAnno")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PImporto")
                        .HasColumnType("TEXT");

                    b.Property<string>("PNote")
                        .HasColumnType("TEXT");

                    b.Property<string>("PRelease")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rda")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseExcel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subco")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MevItems");
                });

            modelBuilder.Entity("MevGovernanceBackend.Models.UserAccessLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LoginAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LogoutAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserAccessLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
