// <auto-generated />
using System;
using MevGovernanceBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace mevgovernancebackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("MevGovernanceBackend.Models.Ambiente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodiceContratto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Ambienti");
                });

            modelBuilder.Entity("MevGovernanceBackend.Models.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastAlignAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LogoutMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TowImpattoJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("MevGovernanceBackend.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLogout")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SendEmail")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MevGovernanceBackend.Models.BuonoConsegna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmbienteId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Avanzato")
                        .HasColumnType("TEXT");

                    b.Property<string>("Contratto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DaAvanzare")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Importo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Oda")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RifContratto")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BuoniConsegna");
                });

            modelBuilder.Entity("MevGovernanceBackend.Models.ConsumoTow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmbienteId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Approvato")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CollaudoApprovato")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CollaudoFatturato")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CollaudoOrdinato")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Impegnato")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCatalogo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("OrdinatiRda")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Residuo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Sconto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tow")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TowApprovati")
                        .HasColumnType("TEXT");

                    b.Property<string>("TowContratto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TowImpegnati")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TowResidui")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValoreTotale")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValoreUnitario")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConsumoTow");
                });

            modelBuilder.Entity("MevGovernanceBackend.Models.Contratto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmbienteId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Avanzato")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DaAvanzare")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DaOrdinare")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImpLordo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImportoNetto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Ordinato")
                        .HasColumnType("TEXT");

                    b.Property<string>("RifContratto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Sconto")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoContratto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contratti");
                });

            modelBuilder.Entity("MevGovernanceBackend.Models.MevItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Accantonato")
                        .HasColumnType("TEXT");

                    b.Property<int>("AmbienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnnoCompetenza")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Applicativo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AtId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapImporti")
                        .HasColumnType("TEXT");

                    b.Property<string>("Capgemini")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Contratto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentoOfferta")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExcelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExcelOrder")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Fatturato")
                        .HasColumnType("TEXT");

                    b.Property<string>("GoTo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Iet")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImportoBdo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImportoExcel")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImportoFornituraScontato")
                        .HasColumnType("TEXT");

                    b.Property<string>("InVita")
                        .HasColumnType("TEXT");

                    b.Property<int>("IsManual")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nel")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteExcel")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OffertaEuro")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OrdinatoBdo")
                        .HasColumnType("TEXT");

                    b.Property<int>("PAnno")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PImporto")
                        .HasColumnType("TEXT");

                    b.Property<string>("PNote")
                        .HasColumnType("TEXT");

                    b.Property<string>("PRelease")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PmCap")
                        .HasColumnType("TEXT");

                    b.Property<string>("PmPoste")
                        .HasColumnType("TEXT");

                    b.Property<string>("Po")
                        .HasColumnType("TEXT");

                    b.Property<string>("PowerAppsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rda")
                        .HasColumnType("TEXT");

                    b.Property<string>("Recupero")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseExcel")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ResiduoFatturabile")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subco")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubcoImporti")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubcoNome")
                        .HasColumnType("TEXT");

                    b.Property<string>("TabellaOfferta")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tbd")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoContratto")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Tow021")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Tow022")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Tow023")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Tow024")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Tow025")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Tow026")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TowTotale")
                        .HasColumnType("TEXT");

                    b.Property<string>("XOrdine")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MevItems");
                });

            modelBuilder.Entity("MevGovernanceBackend.Models.OrdineConsegnaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmbienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ap")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Art")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Contratto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataConsegna")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImportatoDA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportatoIl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Importo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImportoFatturabile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Iniziativa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeseAvanzamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePdf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroOrdine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroRda")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrezzoNetto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QtaAvanzata")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Quantita")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RifContratto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subappalto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoAtt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Um")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OrdiniConsegna");
                });

            modelBuilder.Entity("MevGovernanceBackend.Models.RtiSocietaRiga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmbienteId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Consumato")
                        .HasColumnType("TEXT");

                    b.Property<string>("Contratto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataApprovazione")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataInizio")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Importo")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordine")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Percentuale")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ruolo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Societa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RtiSocietaRighe");
                });

            modelBuilder.Entity("MevGovernanceBackend.Models.UserAccessLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LoginAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LogoutAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserAccessLogs");
                });

            modelBuilder.Entity("MevGovernanceBackend.Models.UserAmbiente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmbienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ruolo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserAmbienti");
                });

            modelBuilder.Entity("MevGovernanceBackend.Models.VerbaleAvanzamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmbienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaricatoDa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CaricatoIl")
                        .HasColumnType("TEXT");

                    b.Property<string>("DatiRigheJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("MeseAvanzamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePdf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RigheAggiornate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RigheElaborate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("VerbaliAvanzamento");
                });
#pragma warning restore 612, 618
        }
    }
}
