// <auto-generated />
using MevGovernanceBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace mevgovernancebackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507140541_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MevGovernanceBackend.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MevGovernanceBackend.Models.MevItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnnoCompetenza")
                        .HasColumnType("integer");

                    b.Property<string>("Applicativo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExcelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExcelOrder")
                        .HasColumnType("integer");

                    b.Property<string>("GoTo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ImportoExcel")
                        .HasColumnType("numeric");

                    b.Property<int>("PAnno")
                        .HasColumnType("integer");

                    b.Property<decimal>("PImporto")
                        .HasColumnType("numeric");

                    b.Property<string>("PNote")
                        .HasColumnType("text");

                    b.Property<string>("PRelease")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MevItems");
                });
#pragma warning restore 612, 618
        }
    }
}
