name: Build and Push Images

on:
  push:
    branches:
      - main

jobs:

  frontend:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v5
        with:
          context: ./mev-governance-ui
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/maurostefanelli/mev-governance-frontend:latest

  backend:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v5
        with:
          context: ./mev-governance-backend
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/maurostefanelli/mev-governance-backend:latest

  parser:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./mev-pdf-parser/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/maurostefanelli/mev-pdf-parser:latest
